input:
    fruit_1: Orange
    fruit_2: Peach
    img_x: 128
    img_y: 128
train:
    n_epochs: 250
    batch_size: 4
    learning_rate: 1e-4
    beta_1: 0.9
    beta_2: 0.99
    alpha_cycle: 10
    alpha_identity: 5
    patch_x: 26
    patch_y: 26
    patch_sep: 25
decay:
    rate: 0.01
    epoch_start: 100
load:
    load_weights: false
    load_epoch: 50
log:
    save_weights: true
    save_imgs: true
    save_weight_interval: 10
    save_image_interval: 10
    save_path: auto
resnet:
    residual_blocks: 9
