input:
    fruit_1: Orange
    fruit_2: Raspberry
    img_x: 128
    img_y: 128
    fruits_file: ../Dataset/dataset_index.csv
    textures_file: ../Dataset/textures_index.csv
    fruits_path: ../Dataset/fruits-360
    textures_path: ../Dataset/textures
    force: True
train:
    n_epochs: 250
    batch_size: 1
    learning_rate: 2e-4
    beta_1: 0.9
    beta_2: 0.99
    alpha_cycle: 10
    alpha_identity: 5
    patch_x: 26
    patch_y: 26
    patch_sep: 25
    test_mode: false
    criterion_gan_loss: MSE
decay:
    rate: 0.01
    epoch_start: 100
load:
    load_weights: false
    load_epoch: 50
log:
    save_weights: true
    save_imgs: true
    save_weight_interval: 10
    save_image_interval: 5
    save_path: auto
    save_path_folder_flag: 'all_losses'
    print_batch_interval: 10
    save_losses: true
resnet:
    residual_blocks: 9
